=== KOST-CECO/eCH-0160/RFC/RFC 2021-16/Mockup/6.mockup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="autor">
		<xs:complexType/>
	</xs:element>
	<xs:element name="bemerkung">
		<xs:complexType/>
	</xs:element>
	<xs:complexType name="bisType">
		<xs:sequence>
			<xs:element ref="datum"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="dateiRefType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="repraesentation" type="xs:string"/>
				<xs:attribute name="reihung" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="datenschutz" type="xs:boolean"/>
	<xs:element name="datum" type="xs:date"/>
	<xs:element name="dokument">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="titel"/>
				<xs:element ref="autor"/>
				<xs:element ref="erscheinungsform"/>
				<xs:element name="entstehungszeitraum" type="entstehungszeitraumType"/>
				<xs:element ref="klassifizierungskategorie"/>
				<xs:element ref="datenschutz"/>
				<xs:element ref="oeffentlichkeitsstatus"/>
				<xs:element ref="oeffentlichkeitsstatusBegruendung"/>
				<xs:element ref="sonstigeBestimmungen"/>
				<xs:element ref="bemerkung"/>
				<xs:element name="zusatzDaten" type="zusatzDatenType"/>
				<xs:element name="dateiRef" type="dateiRefType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="entstehungszeitraumType">
		<xs:sequence>
			<xs:element name="von" type="vonType"/>
			<xs:element name="bis" type="bisType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="erscheinungsform" type="xs:string"/>
	<xs:element name="klassifizierungskategorie" type="xs:string"/>
	<xs:complexType name="merkmalType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="oeffentlichkeitsstatus" type="xs:string"/>
	<xs:element name="oeffentlichkeitsstatusBegruendung">
		<xs:complexType/>
	</xs:element>
	<xs:element name="sonstigeBestimmungen">
		<xs:complexType/>
	</xs:element>
	<xs:element name="titel" type="xs:string"/>
	<xs:complexType name="vonType">
		<xs:sequence>
			<xs:element ref="datum"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="zusatzDatenType">
		<xs:sequence>
			<xs:element name="merkmal" type="merkmalType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== KOST-CECO/eCH-0160/RFC/RFC 2021-16/Mockup/6.ech.v02-mockup.xml
<?xml version="1.0" encoding="UTF-8"?>
<dokument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="6.mockup.xsd">
	<titel>2 Bibliographie</titel>
	<autor/>
	<erscheinungsform>digital</erscheinungsform>
	<entstehungszeitraum>
		<von>
			<datum>2015-05-26</datum>
		</von>
		<bis>
			<datum>2019-04-15</datum>
		</bis>
	</entstehungszeitraum>
	<klassifizierungskategorie>Nicht Klassifiziert</klassifizierungskategorie>
	<datenschutz>false</datenschutz>
	<oeffentlichkeitsstatus>Nicht gepr√ºft</oeffentlichkeitsstatus>
	<oeffentlichkeitsstatusBegruendung/>
	<sonstigeBestimmungen/>
	<bemerkung/>
	<zusatzDaten>
		<merkmal name="Ordnerpfad">\Ordner B docx</merkmal>
		<merkmal name="Parentkey"/>
		<merkmal name="Thema"/>
		<merkmal name="Standort"/>
		<merkmal name="Dokumentdatum">26.05.2015</merkmal>
		<merkmal name="Schutzstufe"/>
		<merkmal name="ForeignDokReference"/>
		<merkmal name="BeschlussNummer"/>
		<merkmal name="SchluesselFremdsystem"/>
		<merkmal name="Tags"/>
	</zusatzDaten>
	<dateiRef repraesentation="2019-04-15T12:01:00" reihung="1">d00001.tif</dateiRef>
	<dateiRef repraesentation="2019-04-15T12:01:00" reihung="2">d00002.tif</dateiRef>
	<dateiRef repraesentation="2019-04-15T12:01:00" reihung="3">d00003.tif</dateiRef>
	<dateiRef repraesentation="2019-04-15T12:01:00" reihung="4">d00004.tif</dateiRef>
	<dateiRef repraesentation="2020-02-09T15:01:00">d000024.pdf</dateiRef>
</dokument>
