=== KOST-CECO/eCH-0160/RFC/RFC 2021-16/Mockup/wrapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="additionalReference">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="secondaryDataLocator" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--  ++++++++++++++++++++++++++++++++++++++++-->
	<xs:complexType name="mdWrapType">
		<xs:sequence>
			<xs:element name="property" type="propertyType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="propertyType">
		<xs:attribute name="key" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<!--  ++++++++++++++++++++++++++++++++++++++++-->
	<xs:simpleType name="xpointerType">
		<xs:annotation>
			<xs:documentation>any xpointer, whitespace collapsed</xs:documentation>
		</xs:annotation>
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:minLength value="1"/>
					<xs:whiteSpace value="collapse"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="emptyType"/>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<!--  ++++++++++++++++++++++++++++++++++++++++-->
	<xs:simpleType name="emptyType">
		<xs:restriction base="xs:string">
			<xs:length value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<!--  ++++++++++++++++++++++++++++++++++++++++-->
	<xs:element name="secondaryDataLocator">
		<xs:complexType mixed="true">
			<xs:annotation>
				<xs:documentation xml:lang="de">Referenz auf einen Objekteintrag in der premis- oder lmerDatei des AIP, damit von dort auf die Prim√§rdatei zugegriffen werden kann, in Form eines xpointer-Eintrags</xs:documentation>
			</xs:annotation>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="mdWrap" type="mdWrapType"/>
			</xs:sequence>
			<xs:attribute name="xpointer" type="xpointerType" use="optional"/>
			<xs:attribute name="obligation" type="xs:string" use="optional" fixed="optional"/>
			<xs:attribute name="archivalOrigin" type="xs:boolean" use="optional"/>
			<xs:attribute name="origin" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KOST-CECO/eCH-0160/RFC/RFC 2021-16/Mockup/wrapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<additionalReference xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Wrapper.xsd">
	<secondaryDataLocator xpointer="premis.xml#ID_C7A0B99F-C0BF-4DB9-B163-B64DF8BFCF89">
		<mdWrap>
			<property key="Version" value="1"/>
			<property key="Renderer" value="00000000000000000000000000000000"/>
			<property key="EingechecktVon" value="Egloff Gregor; GREGOR.EGLOFF@LU.CH"/>
			<property key="CheckInDate" value="15.04.2019 12:01:00"/>
		</mdWrap>
	</secondaryDataLocator>
	<secondaryDataLocator xpointer="premis.xml#ID_E5225E20-F2BB-476D-BC73-A45FE2F9F10E">
		<mdWrap>
			<property key="Version" value="1"/>
			<property key="Renderer" value="0a150a150a150a150a150a150a150a15"/>
			<property key="EingechecktVon" value="0a150a150a150a150a150a150a150a15"/>
			<property key="CheckInDate" value="15.04.2019 12:03:50"/>
		</mdWrap>
	</secondaryDataLocator>
	<secondaryDataLocator>xpointer="premis.xml#ID_E5225E20-F2BB-476D-BC73-A45FE2F9F10E"</secondaryDataLocator>
	<secondaryDataLocator obligation="optional" origin="test" archivalOrigin="true" xpointer="premis.xml#ID_E5225E20-F2BB-476D-BC73-A45FE2F9F10E"/>
</additionalReference>
